var bg = `
SSSSSSSSSSSSSCCSSSSSSSSSSSCSSSCC
CSSSCCSSSCCSSSSSSSSSCSSSCSSSCCSS
SSCCSSSSSCSSSSSSCCSSSCCSSSSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
DDDDDdDddDDDDdDDddDDDDddDDdDDDDd
`.replace(/(\r\n|\n|\r)/gm, "");

var fg = `
#------#-----#------#------#----
`.replace(/(\r\n|\n|\r)/gm, "");